name: churn-imbalanced-dataset

on: [push, pull_request]

permissions:
  contents: write  # needed to post comments on PRs

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Setup CML
        uses: iterative/setup-cml@v1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run inference script
        run: |
          python run_inference.py

      - name: Generate CML report
        run: |
          echo "## Metrics" > report.md

          if [ -f metrics.txt ]; then
            cat metrics.txt >> report.md
          else
            echo "_No metrics.txt found_" >> report.md
          fi

          echo "## Combined Result Image" >> report.md
          if [ -f combined_result.png ]; then
            echo "![](combined_result.png)" >> report.md
          else
            echo "_No combined_result.png found_" >> report.md
          fi

      - name: Post CML comment
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml comment create report.md --reuse
